import { Inter } from "next/font/google";
import { Links } from "./components/NavBar";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Header</h1>
         <Links/>
        <hr />
        {children}       
      </body>
    </html>
  );
}
